FROM python:3.9-slim

WORKDIR /app

# Installation des dépendances système
RUN apt-get update && apt-get install -y \
    && rm -rf /var/lib/apt/lists/*

# Copie des fichiers
COPY requirements.txt .
COPY app.py .
COPY views/ ./views/
COPY img/ ./img/
COPY *.pkl ./
COPY Data/ ./Data/

# Installation des dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]